### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andreaseinsiedler** [owncloud/ios-app#1437]
Steps to reproduce
Open the Files app on iPad
Go to ownCloud on the left panel
Access to the files on the right panel
Expected behavior
Files and folders should be appearing on the right, and we would be able to open them.

Actual behavior
No files or folders are appearing, instead this error message (translated from German) :

"Content unavailable"
"Can't display folder content because of an unknown error"
"Retry"

[ownCloud_24.01.2025__11_34_12.log.txt](https://github.com/user-attachments/files/18534321/ownCloud_24.01.2025__11_34_12.log.txt)

![Image](https://github.com/user-attachments/assets/b5ca73d5-1bc0-4513-94b9-eb6508060dab)

![Image](https://github.com/user-attachments/assets/c5c8b3b4-d275-468f-8339-5c6f81ffeab2)

**Comment by DeepDiver1975** [comment]
This can happen when the os is killing the file provider due to heavy memory consumption - should be fixed in #1416

**Comment by andreaseinsiedler** [comment]
It also happens when the device just booted and files app is the first thing i open.

**Comment by ebin-dev** [comment]
This is a duplicate of bug [#1433](https://github.com/owncloud/ios-app/issues/1433) opened on Dec. 19th.

The owncloud (12.3.1 build 292) - Files app integration was working on iOS 18.1.1 and iPadOS 18.1.1. The issue was introduced with iOS 18.2 and iPadOS 18.2 and is still present on iOS 18.3 and iPadOS 18.3. The bug already occurs if a few nested folders are stored in owncloud (server OC10 and ocis 6.6.1, 7.0.0, and 7.1.0-rc2). 

The Nextcloud (6.2.3.1) - Files app integration is however working fine on all recent iOS and iPadOS versions (Nextcloud server 30.0.5).

Please have a look at this issue since the owncloud - Files integration is essential for working effectively with files on iOS and iPadOS.

**Comment by DeepDiver1975** [comment]
as per #1433 this seems to be fixed in 12.4.0 -> close
