### ISSUE TITLE
iOS Upload Select All (~4000 Pictures) Crashes the App

### ISSUE THREAD

**Issue by alissongodoi** [owncloud/ios-app#405]
### Steps to reproduce
1. Open ownCloud Files application
2. Login into the app
3. Go to the Pictures folder
4. Click to add more files (+)
5. Click to Upload from your photo library
6. Select Camera Roll
7. Select All (around 4000 files)
8. Upload

### Expected behaviour
The app should calculate the metadata for uploading the pictures and queueing them for upload.

### Actual behaviour
The application becomes irresponsive and crashes after 10 seconds. It looks like paging a fixed amount of batches in the background has not been implemented and the iPhone is running out of memory.

### Client
**iOS version:**
12.3.1

**ownCloud app version:**
1.0 build 119

**Device model:**
iPhone X

### Server configuration
**Web server:**
ownCloud 10.2 Docker Image

**Database:**
MariaDB Latest

**PHP version:**
Docker Image Version

**ownCloud version:**
10.2

**Storage backend (external storage):**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
ownCloud Mobile App didn't have any meaningful errors in the log.
```

**Comment by mneuwert** [comment]
@alissongodoi If I look at the version history, the improvements for memory handling during photo upload were merged, after version was set to 119 and hopefully this issue won't be reproducible with build 120.

**Comment by michaelstingl** [comment]
@alissongodoi We released a new TestFlight `Build 123`. Could you give it a try?

**Comment by alissongodoi** [comment]
Well, I don’t know where to start, I am having several issues. 

1) Error 413 for .MOV: 
Couldn’t Upload IMG_5528.MOV.
The operation couldn’t be completed (OCHTTPStatusErrorDomain error 413)

2) I get the error above in all .Mov files. When I cancel the error above for all IMG_XYZV, it keeps coming back in an infinite loop. 

3) when the first error is thrown, there were several images uploaded with the same name: “FullSizeRender.JPG”. This caused several file upload collisions. 

I have a nginx proxy between my Docker image and my host. The error 413 could be from it?

**Comment by felix-schwarz** [comment]
@alissongodoi Thanks for the detailed post! Here's what I found:

1) Error 413 is the status code for `413 Payload Too Large`, indicating that the upload file size exceeds what's allowed by your proxy or OC server.

2+3+4) The image upload currently derives the file name from information it gets from the iOS Photo Library. Much to our own surprise, we noticed that an iOS Photo Library can contain several items by the same name.

When testing the reaction to an error 413 with a single file, both `Cancel` and `Retry` worked as expected. So, like you already suspected, what seemed to be a repeated error message for a single file actually is highly likely the same error message brought up for different files that the iOS Photo Library provided to the app with the same name.

There's no special code path for `.mov` files, so chances are that the `.mov` files you tried to upload exceed the size limit of the proxy or OC server returning the error 413.

5) Right now, all actions are queued and executed as soon as possible, while making sure that actions targeting the same resources are executed in the order they were queued. In your case that means that the folder would only be deleted after all other actions (here: the uploads) have finished.

6) I'd love to look into this, but will need more context - like the exact error message(s) - to do so.

Here's how your issues 1-5 are planned to be addressed in the future:
- for uploads with the same name, the app will eventually pick alternative names if a file with the same name already exists, so you end up with `FullSizeRender.jpg`, `FullSizeRender (2).jpg`, … and won't see any error message in that case.
- as part of extended offline support, the app will become smarter about the meaning of actions, so that deleting a folder to which uploads are still ongoing will cancel the uploads to it, instead of waiting for them to finish

**Comment by alissongodoi** [comment]
@felix-schwarz thanks for the detailed response.

I tried to increase the ownCloud and NGINX Proxy max-size options, however, I am still getting the issues.

Here is the change in the NGINX:
```
client_max_body_size 999M;
```

I have also followed the procedures in the link below. OC comes with a 512M default upload size, which is pretty good:
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/big_file_upload_configuration.html

The funny thing is that I can upload big files via my browser (like 100MB ones), however, via the mobile app, the issue still persists. 

The error is clear that the file is too big, and maybe I need to get my NGINX proxy right. I will keep digging when I have more time.

**Comment by michaelstingl** [comment]
> The funny thing is that I can upload big files via my browser (like 100MB ones), however, via the mobile app, the issue still persists.

@alissongodoi ownCloud web UI and ownCloud desktop sync client use chunked upload. For ownCloud iOS app and ownCloud Android app, this is on the Roadmap, but for now, they upload a single big file.
